/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

/**
 *
 * @author Bhojraj
 */
public class Currency extends javax.swing.JFrame
{

    /**
     * Creates new form Currency
     */
    public Currency()
    {
        initComponents();
        setLocationRelativeTo(null);
        commonFunction.addLabelBackground(lblcross,"C:\\Users\\91976\\Documents\\NetBeansProjects\\GUIAPP3\\src\\main\\java\\mypackage\\images\\cancel.png");
        commonFunction.addLabelBackground(lblhome, "C:\\Users\\91976\\Documents\\NetBeansProjects\\GUIAPP3\\src\\main\\java\\mypackage\\images\\home.png");
        commonFunction.addLabelBackground(lblmoney,"C:\\Users\\91976\\Documents\\NetBeansProjects\\GUIAPP3\\src\\main\\java\\mypackage\\images\\money.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        cmbconvert = new javax.swing.JComboBox<>();
        btncenter = new javax.swing.JButton();
        txtnum = new javax.swing.JTextField();
        lblresult = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblcross = new javax.swing.JLabel();
        lblhome = new javax.swing.JLabel();
        lblmoney = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(203, 218, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Currency Conversion ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 102, 102))); // NOI18N

        cmbconvert.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cmbconvert.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Any One:", "Dollar to Rupees", "Pounds to Rupees", "Rupees to Dollar", "Rupees to Pounds" }));
        cmbconvert.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                cmbconvertItemStateChanged(evt);
            }
        });

        btncenter.setBackground(new java.awt.Color(204, 0, 0));
        btncenter.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btncenter.setForeground(new java.awt.Color(255, 255, 102));
        btncenter.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btncenterActionPerformed(evt);
            }
        });

        txtnum.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtnum.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lblresult.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        lblresult.setForeground(new java.awt.Color(0, 102, 102));
        lblresult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jPanel2.setBackground(new java.awt.Color(99, 145, 221));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Let's Convert");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblcross.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblcrossMouseClicked(evt);
            }
        });

        lblhome.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblhomeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblhome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblcross, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(lblmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmbconvert, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(141, 141, 141)
                                    .addComponent(btncenter, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(169, 169, 169)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(lblresult, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblcross, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblhome, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(cmbconvert, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblmoney, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btncenter, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblresult, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbconvertItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_cmbconvertItemStateChanged
    {//GEN-HEADEREND:event_cmbconvertItemStateChanged
        String str;
        str = (String) cmbconvert.getSelectedItem();
        btncenter.setText(str);

    }//GEN-LAST:event_cmbconvertItemStateChanged

    private void btncenterActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btncenterActionPerformed
    {//GEN-HEADEREND:event_btncenterActionPerformed

        if(btncenter.getActionCommand().equals("Dollar to Rupees"))
        {
            try
            {
                int dol;
                String strmtr;
                strmtr = txtnum.getText();
                dol = Integer.parseInt(strmtr);
                Double rup;
                rup = dol * 73.4225;
                lblresult.setText(dol +" dollar = "+String.valueOf(rup)+" rupees");

            }
            catch (Exception e)
            {
                lblresult.setText("Enter number for conversion");
            }
        }

        if(btncenter.getActionCommand().equals("Pounds to Rupees"))
        {
            try
            {
                int pound;
                String strmtr;
                strmtr = txtnum.getText();
                pound = Integer.parseInt(strmtr);
                Double rup;
                rup = pound * 101.87;
                lblresult.setText(pound +" Pound = "+String.valueOf(rup)+" rupees");
            } catch (Exception e)
            {
                lblresult.setText("Enter number for conversion");
            }
        }

        if(btncenter.getActionCommand().equals("Rupees to Dollar"))
        {
           try
            {
                int rup;
                String strmtr;
                strmtr = txtnum.getText();
                rup = Integer.parseInt(strmtr);
                Double doll;
                doll = rup * 0.0136;
                lblresult.setText(rup +" rupees = "+String.valueOf(doll)+" dollar");
            } catch (Exception e)
            {
                lblresult.setText("Enter number for conversion");
            }
        }

        if(btncenter.getActionCommand().equals("Rupees to Pounds"))
        {
            try
            {
                int rup;
                String strmtr;
                strmtr = txtnum.getText();
                rup = Integer.parseInt(strmtr);
                Double rupee;
                rupee = rup * 0.098;
                lblresult.setText(rup +" rupees = "+String.valueOf(rupee)+" pounds");
            } catch (Exception e)
            {
                lblresult.setText("Enter number for conversion");
            }
        }
    }//GEN-LAST:event_btncenterActionPerformed

    private void lblcrossMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblcrossMouseClicked
    {//GEN-HEADEREND:event_lblcrossMouseClicked
        this.dispose();
    }//GEN-LAST:event_lblcrossMouseClicked

    private void lblhomeMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblhomeMouseClicked
    {//GEN-HEADEREND:event_lblhomeMouseClicked
        firstPage pg = new firstPage();
        this.setVisible(false);
        pg.setVisible(true);
    }//GEN-LAST:event_lblhomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Currency.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Currency().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncenter;
    private javax.swing.JComboBox<String> cmbconvert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblcross;
    private javax.swing.JLabel lblhome;
    private javax.swing.JLabel lblmoney;
    private javax.swing.JLabel lblresult;
    private javax.swing.JTextField txtnum;
    // End of variables declaration//GEN-END:variables
}
